#!/usr/bin/env bash
# This scripts installs nginx and configures it on a remote server
# Requirements:
#   Install nginx on your web-01 server
#   Nginx should be listening on port 80

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
                 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# This starts the nginx service
sudo service nginx start

# This allows nginx on firewall
sudo ufw allow 'Nginx HTTP'

# This gives the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# This will backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# This Creates new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# This restarts nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
