#!/usr/bin/env bash

# Read /etc/passwd line by line

while IFS=: read -r username x uid gid gecos home shell; do
    # Extract relevant information and display them
    echo "$username:$uid:$home"
done < /etc/passwd
