#!/usr/bin/env bash

# Bash script that displays the content of the file /etc/passwd.

# Your script will only display:
# username
# user id
# Home directory path for the user

while IFS=: read -r username x uid gid gecos home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
