#!/usr/bin/env bash

# Bash script that displays the content of the file /etc/passwd.
# Your script will only display:
# username
# user id
# Home directory path for the user

while read -r out; do
    echo "$out" | cut -d ':' -f1,3,6
done </etc/passwd
