#!/usr/bin/env bash
# This script displays "Best School" 10 times and prints "Hi" on the 9th iteration
# Using while and if

a=0

while [ $a -lt 10 ]
do
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi
  	echo "Best School"
	count=$((a+1))
done
