#!/usr/bin/env bash

echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# This allows Outgoing network and denies Incoming network
sudo ufw default deny incoming
sudo ufw default allow outgoing

# This allows ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# This enables Fire Wall
sudo ufw enable

echo -e "Process Completed.\n"
