#!/usr/bin/env bash
# Script that configures Nginx to run as the 'nginx' user and listen on port 8080.

# Update the Nginx configuration to run as the 'nginx' user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify the default site configuration to listen on port 8080 instead of 80
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Change permissions of the nginx.conf file to 644
chmod 644 /etc/nginx/nginx.conf

# If Apache2 is running, stop it to free up port 80
pkill apache2

# Start the Nginx service as the 'nginx' user
sudo -u nginx service nginx start
